import { useState, useEffect } from "react";
import {
    getTasks,
    createTask,
    updateTask,
    completeTask,
    deleteTask,
} from "../services/taskService";
import { getPlants } from "../services/plantService";
import { getCurrentUser } from "../services/authService";
import "./Tasks.css";

function Tasks() {
    const [tasks, setTasks] = useState([]);
    const [plants, setPlants] = useState([]);
    const [currentUser, setCurrentUser] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    // Tabs & Filters
    const [activeTab, setActiveTab] = useState("PENDING"); // 'ALL', 'PENDING', 'COMPLETED'
    const [typeFilter, setTypeFilter] = useState("ALL");
    const [plantFilter, setPlantFilter] = useState("ALL");

    // Modal state
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingTaskId, setEditingTaskId] = useState(null);
    const [saving, setSaving] = useState(false);

    // Form data
    const [formData, setFormData] = useState({
        plantId: "",
        taskType: "WATER",
        scheduledDate: new Date().toISOString().slice(0, 16),
        priority: "MEDIUM",
        notes: "",
        reminderSent: false,
        autoGenerated: false,
    });

    const loadData = async () => {
        setLoading(true);
        setError("");
        try {
            const userData = await getCurrentUser();
            setCurrentUser(userData);

            const [allTasks, userPlants] = await Promise.all([
                getTasks().catch(() => []),
                getPlants(userData.id).catch(() => []),
            ]);

            // Filter tasks for user's plants
            const userPlantIds = new Set(userPlants.map((p) => p.id));
            const filteredUserTasks = userData.role === "ADMIN"
                ? allTasks
                : allTasks.filter((t) => userPlantIds.has(t.plantId));

            setTasks(filteredUserTasks);
            setPlants(userPlants);

            if (userPlants.length > 0 && !formData.plantId) {
                setFormData((prev) => ({ ...prev, plantId: String(userPlants[0].id) }));
            }
        } catch (err) {
            console.error("Error loading tasks:", err);
            setError(err.message || "Failed to load care tasks.");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        loadData();
    }, []);

    const handleOpenModal = (task = null) => {
        if (plants.length === 0) {
            alert("Please add at least one plant before creating care tasks!");
            return;
        }

        if (task) {
            setEditingTaskId(task.id);
            setFormData({
                plantId: String(task.plantId),
                taskType: task.taskType || "WATER",
                scheduledDate: task.scheduledDate
                    ? new Date(task.scheduledDate).toISOString().slice(0, 16)
                    : new Date().toISOString().slice(0, 16),
                priority: task.priority || "MEDIUM",
                notes: task.notes || "",
                reminderSent: task.reminderSent || false,
                autoGenerated: task.autoGenerated || false,
            });
        } else {
            setEditingTaskId(null);
            setFormData({
                plantId: plants[0] ? String(plants[0].id) : "",
                taskType: "WATER",
                scheduledDate: new Date().toISOString().slice(0, 16),
                priority: "MEDIUM",
                notes: "",
                reminderSent: false,
                autoGenerated: false,
            });
        }
        setIsModalOpen(true);
    };

    const handleCloseModal = () => {
        setIsModalOpen(false);
        setEditingTaskId(null);
    };

    const handleFormChange = (e) => {
        const { name, value, type, checked } = e.target;
        setFormData({
            ...formData,
            [name]: type === "checkbox" ? checked : value,
        });
    };

    const handleFormSubmit = async (e) => {
        e.preventDefault();
        if (!formData.plantId) {
            alert("Please select a plant.");
            return;
        }

        setSaving(true);
        try {
            const payload = {
                plantId: Number(formData.plantId),
                taskType: formData.taskType,
                scheduledDate: formData.scheduledDate ? `${formData.scheduledDate}:00` : new Date().toISOString(),
                status: "Pending",
                priority: formData.priority,
                notes: formData.notes?.trim() || null,
                reminderSent: Boolean(formData.reminderSent),
                autoGenerated: Boolean(formData.autoGenerated),
            };

            if (editingTaskId) {
                await updateTask(editingTaskId, payload);
            } else {
                await createTask(payload);
            }

            handleCloseModal();
            loadData();
        } catch (err) {
            alert("Failed to save task: " + err.message);
        } finally {
            setSaving(false);
        }
    };

    // 1-Click Task Completion
    const handleComplete = async (taskId) => {
        try {
            await completeTask(taskId);
            setTasks((prev) =>
                prev.map((t) =>
                    t.id === taskId
                        ? { ...t, status: "Completed", completedDate: new Date().toISOString() }
                        : t
                )
            );
        } catch (err) {
            alert("Failed to complete task: " + err.message);
        }
    };

    // Delete Task
    const handleDelete = async (taskId) => {
        if (window.confirm("Are you sure you want to remove this care task?")) {
            try {
                await deleteTask(taskId);
                setTasks((prev) => prev.filter((t) => t.id !== taskId));
            } catch (err) {
                alert("Failed to delete task: " + err.message);
            }
        }
    };

    // Filter Logic
    const pendingTasks = tasks.filter((t) => t.status?.toLowerCase() !== "completed");
    const completedTasks = tasks.filter((t) => t.status?.toLowerCase() === "completed");

    const displayedTasks = tasks.filter((t) => {
        // Tab filter
        if (activeTab === "PENDING" && t.status?.toLowerCase() === "completed") return false;
        if (activeTab === "COMPLETED" && t.status?.toLowerCase() !== "completed") return false;

        // Type filter
        if (typeFilter !== "ALL" && t.taskType?.toUpperCase() !== typeFilter.toUpperCase()) return false;

        // Plant filter
        if (plantFilter !== "ALL" && String(t.plantId) !== String(plantFilter)) return false;

        return true;
    });

    const getPlantNickname = (plantId) => {
        const found = plants.find((p) => p.id === plantId);
        return found ? found.nickname : `Plant #${plantId}`;
    };

    const getTaskTypeInfo = (type) => {
        switch (type?.toUpperCase()) {
            case "WATER":
            case "WATERING":
                return { label: "Watering", styleClass: "type-water" };
            case "FERTILIZE":
            case "FERTILIZING":
                return { label: "Fertilizing", styleClass: "type-fertilize" };
            case "PRUNE":
            case "PRUNING":
                return { label: "Pruning", styleClass: "type-prune" };
            case "REPOT":
            case "REPOTTING":
                return { label: "Repotting", styleClass: "type-repot" };
            case "MIST":
                return { label: "Misting", styleClass: "type-mist" };
            default:
                return { label: type || "Care", styleClass: "type-general" };
        }
    };

    const getDueDateStatus = (scheduledDateStr) => {
        if (!scheduledDateStr) return { text: "No date set", class: "" };
        const sched = new Date(scheduledDateStr);
        const today = new Date();

        const isToday = sched.toDateString() === today.toDateString();
        if (isToday) return { text: "Due Today", class: "due-indicator-today" };

        if (sched < today) return { text: "Overdue", class: "due-indicator-overdue" };

        return {
            text: `Due ${sched.toLocaleDateString(undefined, { month: "short", day: "numeric" })}`,
            class: "due-indicator-upcoming",
        };
    };

    return (
        <div className="tasks-page">
            {/* Header */}
            <div className="tasks-header">
                <div className="tasks-title-wrap">
                    <span className="tasks-tagline">Care Schedule & Automation</span>
                    <h1>Your Week in Bloom</h1>
                    <p>Weekly tasks, watering cycles, and automated care reminders</p>
                </div>

                <button className="add-task-btn" onClick={() => handleOpenModal()}>
                    Schedule Care Task
                </button>
            </div>

            {/* Quick Metrics Bar */}
            <div className="tasks-metrics-row">
                <div
                    className={`metric-pill-card ${activeTab === "PENDING" ? "active" : ""}`}
                    onClick={() => setActiveTab("PENDING")}
                >
                    <div className="metric-details">
                        <span className="metric-number">{pendingTasks.length}</span>
                        <span className="metric-label">Pending / Due Tasks</span>
                    </div>
                </div>

                <div
                    className={`metric-pill-card ${activeTab === "COMPLETED" ? "active" : ""}`}
                    onClick={() => setActiveTab("COMPLETED")}
                >
                    <div className="metric-details">
                        <span className="metric-number">{completedTasks.length}</span>
                        <span className="metric-label">Completed Tasks</span>
                    </div>
                </div>

                <div
                    className={`metric-pill-card ${activeTab === "ALL" ? "active" : ""}`}
                    onClick={() => setActiveTab("ALL")}
                >
                    <div className="metric-details">
                        <span className="metric-number">{tasks.length}</span>
                        <span className="metric-label">All Schedules</span>
                    </div>
                </div>
            </div>

            {/* Filter Controls */}
            <div className="tasks-controls">
                <select
                    className="filter-select"
                    value={typeFilter}
                    onChange={(e) => setTypeFilter(e.target.value)}
                >
                    <option value="ALL">All Task Types</option>
                    <option value="WATER">Watering</option>
                    <option value="FERTILIZE">Fertilizing</option>
                    <option value="PRUNE">Pruning</option>
                    <option value="REPOT">Repotting</option>
                    <option value="MIST">Misting</option>
                </select>

                <select
                    className="filter-select"
                    value={plantFilter}
                    onChange={(e) => setPlantFilter(e.target.value)}
                >
                    <option value="ALL">All Plants</option>
                    {plants.map((p) => (
                        <option key={p.id} value={String(p.id)}>
                            {p.nickname}
                        </option>
                    ))}
                </select>
            </div>

            {error && <div className="alert-message alert-error">{error}</div>}

            {/* Main Content */}
            {loading ? (
                <div className="dashboard-loading">
                    <div className="dashboard-spinner"></div>
                    <h3>Loading care schedules...</h3>
                </div>
            ) : displayedTasks.length === 0 ? (
                <div className="empty-tasks-box">
                    <h3>
                        {activeTab === "COMPLETED"
                            ? "No completed tasks recorded"
                            : "All caught up! No pending tasks right now."}
                    </h3>
                    <p>
                        {plants.length === 0
                            ? "You don't have any plants yet. Add a plant first to start scheduling care tasks!"
                            : "Create your first watering or fertilizing task schedule."}
                    </p>
                    <button className="add-task-btn" style={{ margin: "0 auto" }} onClick={() => handleOpenModal()}>
                        Schedule a Care Task
                    </button>
                </div>
            ) : (
                <div className="tasks-grid">
                    {displayedTasks.map((task) => {
                        const typeInfo = getTaskTypeInfo(task.taskType);
                        const dueStatus = getDueDateStatus(task.scheduledDate);
                        const isCompleted = task.status?.toLowerCase() === "completed";

                        return (
                            <div
                                key={task.id}
                                className={`task-card ${isCompleted ? "task-completed-card" : ""}`}
                            >
                                <div className="task-card-top">
                                    <span className={`task-type-badge ${typeInfo.styleClass}`}>
                                        {typeInfo.label}
                                    </span>
                                    <span className={`priority-pill priority-${task.priority?.toLowerCase() || "medium"}`}>
                                        {task.priority || "Medium"} Priority
                                    </span>
                                </div>

                                <div className="task-plant-info">
                                    <h3 className="task-plant-name">
                                        {task.plantNickname || getPlantNickname(task.plantId)}
                                    </h3>
                                </div>

                                <div className="task-date-row">
                                    <span className={dueStatus.class}>{dueStatus.text}</span>
                                    <span style={{ color: "#80a58e" }}>•</span>
                                    <span>
                                        {task.scheduledDate
                                            ? new Date(task.scheduledDate).toLocaleTimeString([], {
                                                  hour: "2-digit",
                                                  minute: "2-digit",
                                              })
                                            : ""}
                                    </span>
                                </div>

                                {task.notes && (
                                    <div className="task-notes-box">
                                        {task.notes}
                                    </div>
                                )}

                                <div className="task-card-footer">
                                    {isCompleted ? (
                                        <div className="completed-badge-wrap">
                                            Completed
                                        </div>
                                    ) : (
                                        <button
                                            className="btn-complete-task"
                                            onClick={() => handleComplete(task.id)}
                                        >
                                            Mark as Done
                                        </button>
                                    )}

                                    <div className="task-actions-group">
                                        <button
                                            className="task-icon-btn"
                                            title="Edit task"
                                            onClick={() => handleOpenModal(task)}
                                        >
                                            Edit
                                        </button>
                                        <button
                                            className="task-icon-btn delete"
                                            title="Delete task"
                                            onClick={() => handleDelete(task.id)}
                                        >
                                            Delete
                                        </button>
                                    </div>
                                </div>
                            </div>
                        );
                    })}
                </div>
            )}

            {/* Schedule Task Modal */}
            {isModalOpen && (
                <div className="modal-overlay" onClick={handleCloseModal}>
                    <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                        <div className="modal-header">
                            <h2>{editingTaskId ? "Edit Care Task" : "Schedule Care Task"}</h2>
                            <button className="modal-close-btn" onClick={handleCloseModal}>
                                ✕
                            </button>
                        </div>

                        <form onSubmit={handleFormSubmit} className="modal-form">
                            <div className="form-row">
                                <div className="form-group">
                                    <label>Select Plant *</label>
                                    <select
                                        name="plantId"
                                        value={formData.plantId}
                                        onChange={handleFormChange}
                                        required
                                    >
                                        {plants.map((p) => (
                                            <option key={p.id} value={String(p.id)}>
                                                {p.nickname} ({p.speciesCommonName || "Botanical Specimen"})
                                            </option>
                                        ))}
                                    </select>
                                </div>

                                <div className="form-group">
                                    <label>Task Type *</label>
                                    <select
                                        name="taskType"
                                        value={formData.taskType}
                                        onChange={handleFormChange}
                                        required
                                    >
                                        <option value="WATER">Watering</option>
                                        <option value="FERTILIZE">Fertilizing</option>
                                        <option value="PRUNE">Pruning / Trimming</option>
                                        <option value="REPOT">Repotting</option>
                                        <option value="MIST">Misting Leaves</option>
                                        <option value="GENERAL">General Inspection</option>
                                    </select>
                                </div>
                            </div>

                            <div className="form-row">
                                <div className="form-group">
                                    <label>Scheduled Date & Time *</label>
                                    <input
                                        type="datetime-local"
                                        name="scheduledDate"
                                        value={formData.scheduledDate}
                                        onChange={handleFormChange}
                                        required
                                    />
                                </div>

                                <div className="form-group">
                                    <label>Priority Level *</label>
                                    <select
                                        name="priority"
                                        value={formData.priority}
                                        onChange={handleFormChange}
                                        required
                                    >
                                        <option value="LOW">Low (Routine)</option>
                                        <option value="MEDIUM">Medium (Standard)</option>
                                        <option value="HIGH">High (Urgent)</option>
                                    </select>
                                </div>
                            </div>

                            <div className="form-group">
                                <label>Notes / Instructions (Optional)</label>
                                <textarea
                                    name="notes"
                                    rows="3"
                                    placeholder="e.g. Add 2 pumps of organic fertilizer..."
                                    value={formData.notes}
                                    onChange={handleFormChange}
                                />
                            </div>

                            <div className="modal-actions">
                                <button type="button" className="btn-cancel" onClick={handleCloseModal}>
                                    Cancel
                                </button>
                                <button type="submit" className="btn-save" disabled={saving}>
                                    {saving ? "Scheduling..." : editingTaskId ? "Update Task" : "Schedule Task"}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}

export default Tasks;
