package com.suchitra.plantcarescheduler.mapper;

import org.springframework.stereotype.Component;

import com.suchitra.plantcarescheduler.dto.caretaskdto.CareTaskRequestDTO;
import com.suchitra.plantcarescheduler.dto.caretaskdto.CareTaskResponseDTO;
import com.suchitra.plantcarescheduler.entity.CareTask;

@Component
public class CareTaskMapper {

    // RequestDTO -> Entity
    public CareTask toEntity(CareTaskRequestDTO requestDTO) {

        CareTask task = new CareTask();

        task.setTaskType(requestDTO.getTaskType());
        task.setScheduledDate(requestDTO.getScheduledDate());
        task.setCompletedDate(requestDTO.getCompletedDate());
        task.setStatus(requestDTO.getStatus());
        task.setPriority(requestDTO.getPriority());
        task.setNotes(requestDTO.getNotes());
        task.setReminderSent(requestDTO.isReminderSent());
        task.setAutoGenerated(requestDTO.isAutoGenerated());

        return task;
    }

    // Entity -> ResponseDTO
    public CareTaskResponseDTO toResponseDTO(CareTask task) {

        CareTaskResponseDTO responseDTO = new CareTaskResponseDTO();

        responseDTO.setId(task.getId());

        if (task.getPlant() != null) {
            responseDTO.setPlantId(task.getPlant().getId());
        }

        responseDTO.setTaskType(task.getTaskType());
        responseDTO.setScheduledDate(task.getScheduledDate());
        responseDTO.setCompletedDate(task.getCompletedDate());
        responseDTO.setStatus(task.getStatus());
        responseDTO.setPriority(task.getPriority());
        responseDTO.setNotes(task.getNotes());
        responseDTO.setReminderSent(task.getReminderSent());
        responseDTO.setAutoGenerated(task.getAutoGenerated());

        if (task.getCompletedBy() != null) {
            responseDTO.setCompletedById(task.getCompletedBy().getId());
        }

        responseDTO.setCreatedDate(task.getCreatedDate());

        return responseDTO;
    }

    // Update existing entity
    public void updateEntity(CareTask existingTask, CareTask updatedTask) {

        existingTask.setPlant(updatedTask.getPlant());
        existingTask.setTaskType(updatedTask.getTaskType());
        existingTask.setScheduledDate(updatedTask.getScheduledDate());
        existingTask.setCompletedDate(updatedTask.getCompletedDate());
        existingTask.setStatus(updatedTask.getStatus());
        existingTask.setPriority(updatedTask.getPriority());
        existingTask.setNotes(updatedTask.getNotes());
        existingTask.setReminderSent(updatedTask.getReminderSent());
        existingTask.setAutoGenerated(updatedTask.getAutoGenerated());
        existingTask.setCompletedBy(updatedTask.getCompletedBy());
    }
}