package com.suchitra.plantcarescheduler.dto.caretaskdto;

import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CareTaskResponseDTO {

    private Long id;

    private Long plantId;

    private String taskType;

    private LocalDateTime scheduledDate;

    private LocalDateTime completedDate;

    private String status;

    private String priority;

    private String notes;

    private boolean reminderSent;

    private boolean autoGenerated;

    private Long completedById;

    private LocalDateTime createdDate;
}