package com.suchitra.plantcarescheduler.dto.caretaskdto;

import java.time.LocalDateTime;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CareTaskRequestDTO {

    @NotNull(message = "Plant ID is required")
    private Long plantId;

    @NotBlank(message = "Task type is required")
    private String taskType;

    @NotNull(message = "Scheduled date is required")
    private LocalDateTime scheduledDate;

    private LocalDateTime completedDate;

    @NotBlank(message = "Status is required")
    private String status;

    @NotBlank(message = "Priority is required")
    private String priority;

    private String notes;

    private boolean reminderSent;

    private boolean autoGenerated;

    private Long completedById;
}